sudo: required
dist: trusty
addons:
  artifacts:
    paths:
    - results
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
  - bower_components
  - $HOME/.npm
  - $HOME/.cache
before_script:
- npm install
before_deploy:
- npm run build
env:
  global:
  - NODE_ENV=testing
  - ARTIFACTS_BUCKET=javascript-automation
  - secure: SqXTwhYD8rQzTwTmfwD+O+6JhJ3QAwLcEYMaH8oa9ggVSvgJzYYxvMo+IOYmlRHfWQ7+Kh8yKAiuWK7KC+EiQ8v6kD40lfcSroIhXsZS0PRRLFm/znOm4WLcDyWV/DYiGVWpOJEQV4EUeTXQV8/qxrILbOvPk4lf+YcMF/sTQbHDvyP8YubnT55h9GV6gESGSl2Uis1uzAxizNam2gMi02V7qqfdhHXOoAztlh32Rhs3Gb2zPstLwTIggsBV0t6fBae+nSu+/GfGBiIfB2g8FNofAClFmPwUfSNr0VxEN9/LaJ2siBodCo/5f1IDxmhOLWU2di6ub0wr010fvlgwQ1tYU4MYI89FuQd1U9Nb+soj26SuLWoHRJiqfTKtw5ehPG5c/OEeTnCP+buN2iSoMNKItuz9eJcr4dHR3TVG44a8hnndxPFYUXqWHbIHGTnRqUhnYoyKXwGKXREj8R0peDLl1HarSXlbQyqHZX4O7YkbKsaednyQgpnG3BhyH93ObgiTgL2G69AcOO2DKyX4DxtdPxNfLN9IiZnSQczAu+wgF47JpM8M5KoV2MiNrV0ZshWBz9gZ17WU08nmaMgUXqjB/7L33JutwUzVrsaLHgialT7NnsEK74QfsFqoMnsnmu904mt568bCyFy/A/qNFa0ttLhZg2MSuoZqt2Bl3QU=
  - secure: JBDgwRZsM5SSPlRS5y5BZc/8kSiEAU0jldNv8swY0iO7EXC3ciaqnsj03KuQKkvMDSERKkxG9H+i3EF+V00btR5XDGSRSEdJT1sqIRrWf7nik3+FZ3z+8akMsdZ4LCKExTpwltVq6bnGMSMVwT+Li2LFgnmQzm5ymT/KnXhy043fzs7IZTOq8QblGM24dd0eg54vnrtjjC0wDKSw/osv4fu+Bsptzye5gTvPQdiSzooQ6N54Od6dUpmNx4jm6t5k5DfdzY0zofSFDaZE62YNLThuZOsIxNOgj01y2KrfL2REqlSWiM4FKA+4IryH3jRMCGhLc/vUg2W9kTwjuYpZ34QQQI9UDJfhw/R7/b1iIcDd+gXsuDXHpWx/JIjRAW9atSw7Fn29Ba/LV0jIWN/MbJFuKz1CxljlJvhlv5I3glV3QEolK4o5DccMuwYjgAtTmcF1JVrks97dzGMGcAgH8mqYWxoWMXRPcsIYPLWSnAb7bcEro2gk448VpDu+IIuDBS9oIVBzXatEGE2vNfgJmsAO1/33fnAsVizPCGYN6yAjeYfJW5kNRNScv6znHhRVvY7zqtsjz2t0jiA83bluwBstzcnCZuRAslIhzb3Tg+ETyqVcAg9q+z+lduPu23MyFj5FgmFzZtXfi+32D7OVY9yAxgkamQVi4GFL8pY6RpM=
script:
- npm run test
notifications:
  webhooks: http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build
